# Generated by Django 3.0.8 on 2020-09-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kontak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=70)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('p', 'Pria'), ('w', 'Wanita')], max_length=50)),
                ('alamat', models.TextField()),
                ('agree', models.BooleanField()),
            ],
        ),
    ]
