# Generated by Django 3.0.8 on 2020-10-05 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
                ('slug_cat', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-category'],
            },
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=75, unique=True)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_edit', models.DateField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d')),
                ('slug', models.SlugField(blank=True, max_length=175, unique=True)),
                ('penulis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('post_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', to_field='slug_cat')),
            ],
            options={
                'ordering': ['-date_create'],
                'permissions': {('terbitkan', 'Terbikan Artikel')},
            },
        ),
    ]
